import React, { createContext, useContext, useState } from 'react';

interface LanguageContextType {
  language: 'en' | 'es';
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.booking': 'Book Now',
    'nav.gallery': 'Gallery',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Login',
    'nav.logout': 'Logout',

    // Home Page
    'home.hero.title': 'Discover Your Beauty at MENTHA SALÓN',
    'home.hero.subtitle': 'Premium beauty services with personalized care in a luxurious environment',
    'home.hero.cta': 'Book Your Appointment',
    'home.featured.title': 'Featured Services',
    'home.featured.subtitle': 'Discover our most popular treatments designed to enhance your natural beauty',
    'home.testimonials.title': 'What Our Clients Say',
    'home.testimonials.subtitle': 'Real experiences from our valued clients',
    'home.stats.clients': 'Happy Clients',
    'home.stats.experience': 'Years of Experience',
    'home.stats.services': 'Services Completed',
    'home.stats.rating': 'Average Rating',
    'home.cta.title': 'Ready to Transform Your Look?',
    'home.cta.subtitle': 'Book your appointment today and experience the MENTHA difference',
    'home.cta.book': 'Book Appointment',
    'home.cta.contact': 'Contact Us',
    'home.viewAll': 'View All Services',

    // Service Descriptions
    'service.facial.desc': 'Deep cleansing and rejuvenating facial treatments',
    'service.facial.full': 'Deep cleansing facial with exfoliation and moisturizing treatment',
    'service.haircut.desc': 'Professional haircut with wash, cut, and style consultation',
    'service.coloring.desc': 'Full hair coloring service with premium products',
    'service.highlights.desc': 'Professional highlights to brighten your natural color',
    'service.balayage.desc': 'Natural-looking highlights with seamless color blending',
    'service.balayage.full': 'Hand-painted highlights for natural-looking dimension',
    'service.extensions.desc': 'Premium hair extensions for length and volume',
    'service.blowout.desc': 'Professional blowout styling for any occasion',
    'service.keratin.desc': 'Smoothing keratin treatment for frizz-free hair',
    'service.waxing.desc': 'Professional waxing services for smooth skin',
    'service.eyebrows.desc': 'Precise eyebrow threading for perfect shape',
    'service.lashes.desc': 'Premium eyelash extensions for stunning eyes',
    'service.lashes.full': 'Individual eyelash extensions for stunning eyes',
    'service.makeup.desc': 'Professional makeup application for special events',

    // Testimonials
    'testimonial.1.text': 'Amazing experience! The staff is so professional and the results exceeded my expectations.',
    'testimonial.1.service': 'Balayage & Cut',
    'testimonial.2.text': 'I love coming here! They always make me feel beautiful and pampered. Highly recommended!',
    'testimonial.2.service': 'Facial Treatment',
    'testimonial.3.text': 'The best salon in town! Quality services and such a relaxing atmosphere.',
    'testimonial.3.service': 'Full Service',

    // Services Page
    'services.title': 'Our Services',
    'services.subtitle': 'Transform your look with our comprehensive range of professional beauty services',
    'services.popular': 'Popular',
    'services.cta.title': "Can't Decide? Let Us Help!",
    'services.cta.subtitle': 'Book a consultation with our beauty experts to find the perfect services for you',
    'services.cta.button': 'Schedule Consultation',
    'services.category.all': 'All Services',
    'services.category.hair': 'Hair Services',
    'services.category.facial': 'Facial Treatments',
    'services.category.beauty': 'Beauty Services',
    'services.facial': 'Facial Treatments',
    'services.haircut': 'Hair Cutting',
    'services.coloring': 'Hair Coloring',
    'services.highlights': 'Highlights',
    'services.balayage': 'Balayage',
    'services.extensions': 'Hair Extensions',
    'services.blowout': 'Blowouts',
    'services.keratin': 'Keratin Treatments',
    'services.waxing': 'Hair Removal',
    'services.eyebrows': 'Eyebrow Threading',
    'services.lashes': 'Eyelash Extensions',
    'services.makeup': 'Makeup Application',

    // Booking Page
    'booking.step1.title': 'Select Your Service',
    'booking.step2.title': 'Choose Date & Time',
    'booking.step3.title': 'Your Information',
    'booking.step4.title': 'Confirm & Pay',
    'booking.step1.short': 'Select Service',
    'booking.step2.short': 'Date & Time',
    'booking.step3.short': 'Your Info',
    'booking.step4.short': 'Confirm & Pay',
    'booking.selectDate': 'Select Date',
    'booking.selectTime': 'Select Time',
    'booking.preferredSpecialist': 'Preferred Specialist',
    'booking.fullName': 'Full Name',
    'booking.email': 'Email Address',
    'booking.phone': 'Phone Number',
    'booking.specialNotes': 'Special Notes (Optional)',
    'booking.notesPlaceholder': 'Any special requests or notes...',
    'booking.namePlaceholder': 'Enter your full name',
    'booking.emailPlaceholder': 'Enter your email',
    'booking.phonePlaceholder': 'Enter your phone number',
    'booking.summary': 'Booking Summary',
    'booking.service': 'Service:',
    'booking.dateTime': 'Date & Time:',
    'booking.specialist': 'Specialist:',
    'booking.duration': 'Duration:',
    'booking.minutes': 'minutes',
    'booking.total': 'Total:',
    'booking.payment': 'Payment Information',
    'booking.cardNumber': 'Card Number',
    'booking.expiryDate': 'Expiry Date',
    'booking.cvc': 'CVC',
    'booking.cancellation': 'Cancellation Policy:',
    'booking.cancellationText': 'You can cancel or reschedule your appointment up to 24 hours before your scheduled time without penalty.',
    'booking.previous': 'Previous',
    'booking.next': 'Next Step',
    'booking.confirm': 'Confirm Booking',
    'booking.confirmAlert': 'Booking confirmed! You will receive a confirmation email shortly.',
    'booking.staff.specialty.hair': 'Hair Specialist',
    'booking.staff.specialty.facial': 'Facial Expert',
    'booking.staff.specialty.beauty': 'Beauty Specialist',
    'booking.staff.specialty.any': 'Best Match',
    'booking.staff.anyAvailable': 'Any Available',

    // About Page
    'about.title': 'About MENTHA SALÓN',
    'about.subtitle': "For over a decade, we've been dedicated to enhancing natural beauty through exceptional service, expert techniques, and a commitment to making every client feel confident and beautiful.",
    'about.story.title': 'Our Story',
    'about.story.p1': 'MENTHA SALÓN was born from a passion for beauty and a vision to create a sanctuary where clients could escape, relax, and emerge feeling more confident than ever. Founded in 2014 by Ana Rodriguez, our salon has grown from a small neighborhood beauty destination to a premier luxury salon serving the community.',
    'about.story.p2': 'Our name "MENTHA" represents freshness, renewal, and natural beauty – values that are at the heart of everything we do. We believe that beauty is personal, and our approach is always tailored to enhance each client\'s unique features and style.',
    'about.story.p3': 'Today, we continue to evolve while staying true to our core mission: providing exceptional beauty services in an environment where luxury meets comfort, and every client leaves feeling their absolute best.',
    'about.stats.experience': 'Years of Excellence',
    'about.stats.clients': 'Happy Clients',
    'about.stats.services': 'Services Completed',
    'about.stats.rating': 'Average Rating',
    'about.values.title': 'Our Values',
    'about.values.subtitle': 'The principles that guide everything we do at MENTHA SALÓN',
    'about.values.clientCare': 'Client-Centered Care',
    'about.values.clientCareDesc': 'Every service is personalized to meet your unique beauty goals and lifestyle needs.',
    'about.values.excellence': 'Excellence in Service',
    'about.values.excellenceDesc': 'We maintain the highest standards in technique, products, and customer experience.',
    'about.values.expertTeam': 'Expert Team',
    'about.values.expertTeamDesc': 'Our skilled professionals stay current with the latest trends and techniques.',
    'about.values.luxury': 'Luxury Experience',
    'about.values.luxuryDesc': 'From ambiance to amenities, every detail is designed for your comfort and relaxation.',
    'about.team.title': 'Meet Our Expert Team',
    'about.team.subtitle': 'Passionate professionals dedicated to bringing out your natural beauty',
    'about.team.founder': 'Founder & Senior Stylist',
    'about.team.facialSpecialist': 'Facial Specialist',
    'about.team.beautySpecialist': 'Beauty Specialist',
    'about.team.juniorStylist': 'Junior Stylist',
    'about.team.ana.bio': 'Ana founded MENTHA SALÓN with a vision to create a luxurious beauty destination. Specializing in creative color techniques and precision cuts.',
    'about.team.sofia.bio': 'Sofia brings expertise in advanced facial treatments and holistic skincare approaches to help clients achieve their healthiest skin.',
    'about.team.lucia.bio': 'Lucia specializes in creating stunning eye looks and flawless makeup applications for all occasions, from everyday to bridal.',
    'about.team.carmen.bio': "Carmen is passionate about creating modern, wearable styles that enhance each client's individual beauty and lifestyle.",
    'about.journey.title': 'Our Journey',
    'about.journey.subtitle': 'Key milestones in our commitment to beauty excellence',
    'about.visit.title': 'Visit Our Salon',
    'about.visit.subtitle': 'Experience the MENTHA difference in our beautifully designed space',
    'about.visit.location': 'Location',
    'about.visit.hours': 'Hours',
    'about.visit.cta.title': 'Ready to Experience MENTHA?',
    'about.visit.cta.subtitle': 'Book your appointment today and discover why our clients choose us for all their beauty needs.',
    'about.visit.book': 'Book Appointment',
    'about.visit.contact': 'Contact Us',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': "Have questions or ready to book? We'd love to hear from you. Get in touch with our team today.",
    'contact.visit': 'Visit Us',
    'contact.details': 'Contact Details',
    'contact.hours': 'Hours',
    'contact.getDirections': 'Get Directions',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.monday': 'Monday - Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.form.title': 'Send us a Message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.service': 'Service of Interest',
    'contact.form.selectService': 'Select a service',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Tell us how we can help you...',
    'contact.form.namePlaceholder': 'Your full name',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.phonePlaceholder': '(555) 123-4567',
    'contact.form.send': 'Send Message',
    'contact.form.success': 'Thank you for your message! We will get back to you soon.',
    'contact.actions.bookOnline': 'Book Online',
    'contact.actions.bookOnlineDesc': 'Schedule your appointment online 24/7 with our easy booking system.',
    'contact.actions.bookNow': 'Book Now',
    'contact.actions.callUs': 'Call Us',
    'contact.actions.callUsDesc': 'Speak with our team directly for personalized service and consultation.',
    'contact.actions.callNow': 'Call Now',
    'contact.actions.visitUs': 'Visit Us',
    'contact.actions.visitUsDesc': 'Come visit our beautiful salon and experience the MENTHA difference.',
    'contact.map.title': 'Find Us',
    'contact.map.label': 'Interactive Map',
    'contact.serviceOther': 'Other',

    // Login Page
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to your account to access your dashboard',
    'login.demoCredentials': 'Demo Credentials:',
    'login.customer': 'Customer',
    'login.staff': 'Staff',
    'login.password': 'password',
    'login.emailLabel': 'Email Address',
    'login.emailPlaceholder': 'Enter your email',
    'login.passwordLabel': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.noAccount': "Don't have an account?",
    'login.contactUs': 'Contact us to get started',
    'login.terms': 'By signing in, you agree to our',
    'login.termsLink': 'Terms of Service',
    'login.and': 'and',
    'login.privacyLink': 'Privacy Policy',
    'login.errorInvalid': 'Invalid email or password. Please try again.',
    'login.errorFailed': 'Login failed. Please try again.',

    // Staff Dashboard
    'staff.title': 'Staff Dashboard',
    'staff.welcome': 'Welcome back',
    'staff.overview': 'Here\'s your daily overview.',
    'staff.tabs.overview': 'Overview',
    'staff.tabs.schedule': 'Schedule',
    'staff.tabs.clients': 'Clients',
    'staff.tabs.performance': 'Performance',
    'staff.stats.todayAppointments': 'Today\'s Appointments',
    'staff.stats.todayRevenue': 'Today\'s Revenue',
    'staff.stats.weeklyRevenue': 'Weekly Revenue',
    'staff.stats.averageRating': 'Average Rating',
    'staff.todaySchedule': 'Today\'s Schedule',
    'staff.status.confirmed': 'confirmed',
    'staff.status.inProgress': 'in-progress',
    'staff.status.upcoming': 'upcoming',
    'staff.schedule.title': 'Weekly Schedule',
    'staff.schedule.blockTime': 'Block Time',
    'staff.schedule.addAppointment': 'Add Appointment',
    'staff.schedule.appointments': 'appointments',
    'staff.schedule.calendarNote': 'Detailed calendar view would be implemented here',
    'staff.clients.title': 'Client Management',
    'staff.clients.addNew': 'Add New Client',
    'staff.clients.recent': 'Recent Clients',
    'staff.clients.search': 'Search clients...',
    'staff.clients.name': 'Name',
    'staff.clients.lastVisit': 'Last Visit',
    'staff.clients.totalSpent': 'Total Spent',
    'staff.clients.visits': 'Visits',
    'staff.clients.rating': 'Rating',
    'staff.clients.actions': 'Actions',
    'staff.clients.viewDetails': 'View Details',
    'staff.performance.title': 'Performance Analytics',
    'staff.performance.monthly': 'Monthly Performance',
    'staff.performance.revenue': 'Revenue',
    'staff.performance.appointments': 'Appointments',
    'staff.performance.clientRetention': 'Client Retention',
    'staff.performance.popularServices': 'Popular Services',
    'staff.performance.monthlyGoals': 'Monthly Goals',
    'staff.performance.revenueGoal': 'Revenue Goal',
    'staff.performance.appointmentsGoal': 'Appointments Goal',
    'staff.performance.ratingGoal': 'Rating Goal',
    'staff.days.monday': 'Monday',
    'staff.days.tuesday': 'Tuesday',
    'staff.days.wednesday': 'Wednesday',
    'staff.days.thursday': 'Thursday',
    'staff.days.friday': 'Friday',
    'staff.days.saturday': 'Saturday',
    'staff.days.sunday': 'Sunday',

    // Admin Page
    'admin.title': 'Admin Panel',
    'admin.subtitle': 'Manage all salon appointments',
    'admin.stats.total': 'Total Appointments',
    'admin.stats.pending': 'Pending',
    'admin.stats.confirmed': 'Confirmed',
    'admin.stats.completed': 'Completed',
    'admin.filter.all': 'All',
    'admin.filter.pending': 'Pending',
    'admin.filter.confirmed': 'Confirmed',
    'admin.filter.completed': 'Completed',
    'admin.filter.canceled': 'Canceled',
    'admin.noAppointments': 'No appointments in this category',
    'admin.client': 'Client',
    'admin.notes': 'Notes',
    'admin.actions.confirm': 'Confirm',
    'admin.actions.complete': 'Complete',
    'admin.actions.cancel': 'Cancel',
    'admin.actions.delete': 'Delete',
    'admin.deleteConfirm': 'Are you sure you want to delete this appointment?',
    'admin.status.pending': 'Pending',
    'admin.status.confirmed': 'Confirmed',
    'admin.status.completed': 'Completed',
    'admin.status.canceled': 'Canceled',

    // Booking Page (New)
    'booking.new.title': 'Book Your Appointment',
    'booking.new.subtitle': 'Select your service and preferred time',
    'booking.new.success': 'Appointment booked successfully! We will contact you soon to confirm.',
    'booking.new.personalInfo': 'Personal Information',
    'booking.new.fullName': 'Full Name',
    'booking.new.fullNamePlaceholder': 'Your full name',
    'booking.new.phone': 'Phone',
    'booking.new.phonePlaceholder': '(555) 123-4567',
    'booking.new.email': 'Email',
    'booking.new.emailPlaceholder': 'your@email.com',
    'booking.new.selectService': 'Select a Service',
    'booking.new.dateTime': 'Date & Time',
    'booking.new.date': 'Date',
    'booking.new.time': 'Time',
    'booking.new.selectTime': 'Select a time',
    'booking.new.additionalNotes': 'Additional Notes (Optional)',
    'booking.new.notesPlaceholder': 'Any special preferences or requests?',
    'booking.new.bookButton': 'Book Appointment',
    'booking.new.booking': 'Booking...',
    'booking.new.required': '*',

    // Gallery Page
    'gallery.title': 'Our Work Gallery',
    'gallery.subtitle': 'Explore our stunning transformations and get inspired for your next beauty journey',
    'gallery.searchPlaceholder': 'Search by style, service, or tag...',
    'gallery.filter': 'Filter',
    'gallery.categories': 'Categories',
    'gallery.allWork': 'All Work',
    'gallery.hairCuts': 'Hair Cuts',
    'gallery.hairColor': 'Hair Color',
    'gallery.viewDetails': 'View Details',
    'gallery.noResults': 'No results found',
    'gallery.noResultsDesc': "Try adjusting your search or filter criteria to find what you're looking for.",
    'gallery.cta.title': 'Ready for Your Transformation?',
    'gallery.cta.subtitle': 'Book your appointment today and let our experts create your perfect look',
    'gallery.cta.book': 'Book Now',
    'gallery.cta.instagram': 'Follow on Instagram',

    // Footer
    'footer.description': 'Experience luxury beauty services with personalized care in our modern salon environment. Your beauty transformation awaits.',
    'footer.hours': 'Hours',
    'footer.monday': 'Mon - Fri',
    'footer.saturday': 'Saturday',
    'footer.sunday': 'Sunday',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cancellation': 'Cancellation Policy',

    // Common
    'common.book': 'Book Now',
    'common.learnMore': 'Learn More',
    'common.price': 'Price',
    'common.duration': 'Duration',
    'common.contact': 'Contact Us',
    'common.required': '*',
    'common.at': 'at',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.booking': 'Reservar',
    'nav.gallery': 'Galería',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'nav.dashboard': 'Panel',
    'nav.login': 'Iniciar Sesión',
    'nav.logout': 'Cerrar Sesión',

    // Home Page
    'home.hero.title': 'Descubre Tu Belleza en MENTHA SALÓN',
    'home.hero.subtitle': 'Servicios de belleza premium con cuidado personalizado en un ambiente lujoso',
    'home.hero.cta': 'Reserva Tu Cita',
    'home.featured.title': 'Servicios Destacados',
    'home.featured.subtitle': 'Descubre nuestros tratamientos más populares diseñados para realzar tu belleza natural',
    'home.testimonials.title': 'Lo Que Dicen Nuestros Clientes',
    'home.testimonials.subtitle': 'Experiencias reales de nuestros valiosos clientes',
    'home.stats.clients': 'Clientes Felices',
    'home.stats.experience': 'Años de Experiencia',
    'home.stats.services': 'Servicios Completados',
    'home.stats.rating': 'Calificación Promedio',
    'home.cta.title': '¿Listo para Transformar Tu Look?',
    'home.cta.subtitle': 'Reserva tu cita hoy y experimenta la diferencia MENTHA',
    'home.cta.book': 'Reservar Cita',
    'home.cta.contact': 'Contáctanos',
    'home.viewAll': 'Ver Todos los Servicios',

    // Service Descriptions
    'service.facial.desc': 'Tratamientos faciales de limpieza profunda y rejuvenecimiento',
    'service.facial.full': 'Limpieza facial profunda con exfoliación y tratamiento hidratante',
    'service.haircut.desc': 'Corte profesional con lavado, corte y consulta de estilo',
    'service.coloring.desc': 'Servicio completo de color de cabello con productos premium',
    'service.highlights.desc': 'Reflejos profesionales para iluminar tu color natural',
    'service.balayage.desc': 'Reflejos de aspecto natural con mezcla de color perfecta',
    'service.balayage.full': 'Reflejos pintados a mano para dimensión de aspecto natural',
    'service.extensions.desc': 'Extensiones de cabello premium para longitud y volumen',
    'service.blowout.desc': 'Peinado profesional con secador para cualquier ocasión',
    'service.keratin.desc': 'Tratamiento alisador de queratina para cabello sin frizz',
    'service.waxing.desc': 'Servicios profesionales de depilación para piel suave',
    'service.eyebrows.desc': 'Depilación precisa de cejas con hilo para forma perfecta',
    'service.lashes.desc': 'Extensiones de pestañas premium para ojos impresionantes',
    'service.lashes.full': 'Extensiones de pestañas individuales para ojos impresionantes',
    'service.makeup.desc': 'Aplicación profesional de maquillaje para eventos especiales',

    // Testimonials
    'testimonial.1.text': '¡Experiencia increíble! El personal es muy profesional y los resultados superaron mis expectativas.',
    'testimonial.1.service': 'Balayage y Corte',
    'testimonial.2.text': '¡Me encanta venir aquí! Siempre me hacen sentir hermosa y consentida. ¡Muy recomendado!',
    'testimonial.2.service': 'Tratamiento Facial',
    'testimonial.3.text': '¡El mejor salón de la ciudad! Servicios de calidad y una atmósfera tan relajante.',
    'testimonial.3.service': 'Servicio Completo',

    // Services Page
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Transforma tu look con nuestra amplia gama de servicios profesionales de belleza',
    'services.popular': 'Popular',
    'services.cta.title': '¿No Puedes Decidir? ¡Déjanos Ayudarte!',
    'services.cta.subtitle': 'Reserva una consulta con nuestros expertos en belleza para encontrar los servicios perfectos para ti',
    'services.cta.button': 'Agendar Consulta',
    'services.category.all': 'Todos los Servicios',
    'services.category.hair': 'Servicios de Cabello',
    'services.category.facial': 'Tratamientos Faciales',
    'services.category.beauty': 'Servicios de Belleza',
    'services.facial': 'Tratamientos Faciales',
    'services.haircut': 'Corte de Cabello',
    'services.coloring': 'Color de Cabello',
    'services.highlights': 'Reflejos',
    'services.balayage': 'Balayage',
    'services.extensions': 'Extensiones de Cabello',
    'services.blowout': 'Peinados/Brushing',
    'services.keratin': 'Tratamiento de Queratina',
    'services.waxing': 'Depilación',
    'services.eyebrows': 'Depilación de Cejas con Hilo',
    'services.lashes': 'Extensiones de Pestañas',
    'services.makeup': 'Aplicación de Maquillaje',

    // Booking Page
    'booking.step1.title': 'Selecciona Tu Servicio',
    'booking.step2.title': 'Elige Fecha y Hora',
    'booking.step3.title': 'Tu Información',
    'booking.step4.title': 'Confirmar y Pagar',
    'booking.step1.short': 'Seleccionar Servicio',
    'booking.step2.short': 'Fecha y Hora',
    'booking.step3.short': 'Tu Info',
    'booking.step4.short': 'Confirmar y Pagar',
    'booking.selectDate': 'Seleccionar Fecha',
    'booking.selectTime': 'Seleccionar Hora',
    'booking.preferredSpecialist': 'Especialista Preferido',
    'booking.fullName': 'Nombre Completo',
    'booking.email': 'Correo Electrónico',
    'booking.phone': 'Número de Teléfono',
    'booking.specialNotes': 'Notas Especiales (Opcional)',
    'booking.notesPlaceholder': 'Cualquier solicitud o nota especial...',
    'booking.namePlaceholder': 'Ingresa tu nombre completo',
    'booking.emailPlaceholder': 'Ingresa tu correo',
    'booking.phonePlaceholder': 'Ingresa tu número de teléfono',
    'booking.summary': 'Resumen de Reserva',
    'booking.service': 'Servicio:',
    'booking.dateTime': 'Fecha y Hora:',
    'booking.specialist': 'Especialista:',
    'booking.duration': 'Duración:',
    'booking.minutes': 'minutos',
    'booking.total': 'Total:',
    'booking.payment': 'Información de Pago',
    'booking.cardNumber': 'Número de Tarjeta',
    'booking.expiryDate': 'Fecha de Vencimiento',
    'booking.cvc': 'CVC',
    'booking.cancellation': 'Política de Cancelación:',
    'booking.cancellationText': 'Puedes cancelar o reprogramar tu cita hasta 24 horas antes de tu hora programada sin penalización.',
    'booking.previous': 'Anterior',
    'booking.next': 'Siguiente Paso',
    'booking.confirm': 'Confirmar Reserva',
    'booking.confirmAlert': '¡Reserva confirmada! Recibirás un correo de confirmación en breve.',
    'booking.staff.specialty.hair': 'Especialista en Cabello',
    'booking.staff.specialty.facial': 'Experta en Faciales',
    'booking.staff.specialty.beauty': 'Especialista en Belleza',
    'booking.staff.specialty.any': 'Mejor Opción',
    'booking.staff.anyAvailable': 'Cualquier Disponible',

    // About Page
    'about.title': 'Acerca de MENTHA SALÓN',
    'about.subtitle': 'Durante más de una década, nos hemos dedicado a realzar la belleza natural a través de un servicio excepcional, técnicas expertas y un compromiso de hacer que cada cliente se sienta segura y hermosa.',
    'about.story.title': 'Nuestra Historia',
    'about.story.p1': 'MENTHA SALÓN nació de una pasión por la belleza y una visión de crear un santuario donde los clientes pudieran escapar, relajarse y salir sintiéndose más seguros que nunca. Fundado en 2014 por Ana Rodríguez, nuestro salón ha crecido de ser un pequeño destino de belleza vecinal a un salón de lujo premier sirviendo a la comunidad.',
    'about.story.p2': 'Nuestro nombre "MENTHA" representa frescura, renovación y belleza natural: valores que están en el corazón de todo lo que hacemos. Creemos que la belleza es personal, y nuestro enfoque siempre está adaptado para realzar las características únicas y el estilo de cada cliente.',
    'about.story.p3': 'Hoy, continuamos evolucionando mientras nos mantenemos fieles a nuestra misión principal: proporcionar servicios de belleza excepcionales en un ambiente donde el lujo se encuentra con la comodidad, y cada cliente se va sintiéndose en su mejor momento.',
    'about.stats.experience': 'Años de Excelencia',
    'about.stats.clients': 'Clientes Felices',
    'about.stats.services': 'Servicios Completados',
    'about.stats.rating': 'Calificación Promedio',
    'about.values.title': 'Nuestros Valores',
    'about.values.subtitle': 'Los principios que guían todo lo que hacemos en MENTHA SALÓN',
    'about.values.clientCare': 'Cuidado Centrado en el Cliente',
    'about.values.clientCareDesc': 'Cada servicio está personalizado para cumplir con tus objetivos únicos de belleza y necesidades de estilo de vida.',
    'about.values.excellence': 'Excelencia en el Servicio',
    'about.values.excellenceDesc': 'Mantenemos los más altos estándares en técnica, productos y experiencia del cliente.',
    'about.values.expertTeam': 'Equipo Experto',
    'about.values.expertTeamDesc': 'Nuestros profesionales capacitados se mantienen actualizados con las últimas tendencias y técnicas.',
    'about.values.luxury': 'Experiencia de Lujo',
    'about.values.luxuryDesc': 'Desde el ambiente hasta las comodidades, cada detalle está diseñado para tu comodidad y relajación.',
    'about.team.title': 'Conoce a Nuestro Equipo Experto',
    'about.team.subtitle': 'Profesionales apasionados dedicados a resaltar tu belleza natural',
    'about.team.founder': 'Fundadora y Estilista Senior',
    'about.team.facialSpecialist': 'Especialista en Faciales',
    'about.team.beautySpecialist': 'Especialista en Belleza',
    'about.team.juniorStylist': 'Estilista Junior',
    'about.team.ana.bio': 'Ana fundó MENTHA SALÓN con la visión de crear un destino de belleza lujoso. Se especializa en técnicas creativas de color y cortes de precisión.',
    'about.team.sofia.bio': 'Sofia aporta experiencia en tratamientos faciales avanzados y enfoques holísticos del cuidado de la piel para ayudar a los clientes a lograr su piel más saludable.',
    'about.team.lucia.bio': 'Lucia se especializa en crear looks de ojos impresionantes y aplicaciones de maquillaje impecables para todas las ocasiones, desde lo cotidiano hasta novias.',
    'about.team.carmen.bio': 'Carmen es apasionada por crear estilos modernos y usables que realzan la belleza individual y el estilo de vida de cada cliente.',
    'about.journey.title': 'Nuestro Recorrido',
    'about.journey.subtitle': 'Hitos clave en nuestro compromiso con la excelencia en belleza',
    'about.visit.title': 'Visita Nuestro Salón',
    'about.visit.subtitle': 'Experimenta la diferencia MENTHA en nuestro espacio bellamente diseñado',
    'about.visit.location': 'Ubicación',
    'about.visit.hours': 'Horario',
    'about.visit.cta.title': '¿Lista para Experimentar MENTHA?',
    'about.visit.cta.subtitle': 'Reserva tu cita hoy y descubre por qué nuestros clientes nos eligen para todas sus necesidades de belleza.',
    'about.visit.book': 'Reservar Cita',
    'about.visit.contact': 'Contáctanos',

    // Contact Page
    'contact.title': 'Contáctanos',
    'contact.subtitle': '¿Tienes preguntas o listo para reservar? Nos encantaría saber de ti. Ponte en contacto con nuestro equipo hoy.',
    'contact.visit': 'Visítanos',
    'contact.details': 'Detalles de Contacto',
    'contact.hours': 'Horario',
    'contact.getDirections': 'Obtener Direcciones',
    'contact.phone': 'Teléfono',
    'contact.email': 'Correo',
    'contact.monday': 'Lunes - Viernes',
    'contact.saturday': 'Sábado',
    'contact.sunday': 'Domingo',
    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.phone': 'Número de Teléfono',
    'contact.form.service': 'Servicio de Interés',
    'contact.form.selectService': 'Selecciona un servicio',
    'contact.form.message': 'Mensaje',
    'contact.form.messagePlaceholder': 'Cuéntanos cómo podemos ayudarte...',
    'contact.form.namePlaceholder': 'Tu nombre completo',
    'contact.form.emailPlaceholder': 'tu@correo.com',
    'contact.form.phonePlaceholder': '(555) 123-4567',
    'contact.form.send': 'Enviar Mensaje',
    'contact.form.success': '¡Gracias por tu mensaje! Te responderemos pronto.',
    'contact.actions.bookOnline': 'Reserva en Línea',
    'contact.actions.bookOnlineDesc': 'Programa tu cita en línea las 24 horas con nuestro sistema de reservas fácil.',
    'contact.actions.bookNow': 'Reservar Ahora',
    'contact.actions.callUs': 'Llámanos',
    'contact.actions.callUsDesc': 'Habla con nuestro equipo directamente para servicio personalizado y consulta.',
    'contact.actions.callNow': 'Llamar Ahora',
    'contact.actions.visitUs': 'Visítanos',
    'contact.actions.visitUsDesc': 'Ven a visitar nuestro hermoso salón y experimenta la diferencia MENTHA.',
    'contact.map.title': 'Encuéntranos',
    'contact.map.label': 'Mapa Interactivo',
    'contact.serviceOther': 'Otro',

    // Login Page
    'login.title': 'Bienvenido de Nuevo',
    'login.subtitle': 'Inicia sesión en tu cuenta para acceder a tu panel',
    'login.demoCredentials': 'Credenciales de Prueba:',
    'login.customer': 'Cliente',
    'login.staff': 'Personal',
    'login.password': 'contraseña',
    'login.emailLabel': 'Correo Electrónico',
    'login.emailPlaceholder': 'Ingresa tu correo',
    'login.passwordLabel': 'Contraseña',
    'login.passwordPlaceholder': 'Ingresa tu contraseña',
    'login.rememberMe': 'Recuérdame',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.signIn': 'Iniciar Sesión',
    'login.signingIn': 'Iniciando sesión...',
    'login.noAccount': '¿No tienes una cuenta?',
    'login.contactUs': 'Contáctanos para empezar',
    'login.terms': 'Al iniciar sesión, aceptas nuestros',
    'login.termsLink': 'Términos de Servicio',
    'login.and': 'y',
    'login.privacyLink': 'Política de Privacidad',
    'login.errorInvalid': 'Correo o contraseña inválidos. Por favor intenta de nuevo.',
    'login.errorFailed': 'Error al iniciar sesión. Por favor intenta de nuevo.',

    // Staff Dashboard
    'staff.title': 'Panel del Personal',
    'staff.welcome': 'Bienvenido de nuevo',
    'staff.overview': 'Aquí está tu resumen diario.',
    'staff.tabs.overview': 'Resumen',
    'staff.tabs.schedule': 'Horario',
    'staff.tabs.clients': 'Clientes',
    'staff.tabs.performance': 'Rendimiento',
    'staff.stats.todayAppointments': 'Citas de Hoy',
    'staff.stats.todayRevenue': 'Ingresos de Hoy',
    'staff.stats.weeklyRevenue': 'Ingresos Semanales',
    'staff.stats.averageRating': 'Calificación Promedio',
    'staff.todaySchedule': 'Horario de Hoy',
    'staff.status.confirmed': 'confirmada',
    'staff.status.inProgress': 'en-progreso',
    'staff.status.upcoming': 'próxima',
    'staff.schedule.title': 'Horario Semanal',
    'staff.schedule.blockTime': 'Bloquear Tiempo',
    'staff.schedule.addAppointment': 'Agregar Cita',
    'staff.schedule.appointments': 'citas',
    'staff.schedule.calendarNote': 'La vista detallada del calendario se implementaría aquí',
    'staff.clients.title': 'Gestión de Clientes',
    'staff.clients.addNew': 'Agregar Nuevo Cliente',
    'staff.clients.recent': 'Clientes Recientes',
    'staff.clients.search': 'Buscar clientes...',
    'staff.clients.name': 'Nombre',
    'staff.clients.lastVisit': 'Última Visita',
    'staff.clients.totalSpent': 'Total Gastado',
    'staff.clients.visits': 'Visitas',
    'staff.clients.rating': 'Calificación',
    'staff.clients.actions': 'Acciones',
    'staff.clients.viewDetails': 'Ver Detalles',
    'staff.performance.title': 'Análisis de Rendimiento',
    'staff.performance.monthly': 'Rendimiento Mensual',
    'staff.performance.revenue': 'Ingresos',
    'staff.performance.appointments': 'Citas',
    'staff.performance.clientRetention': 'Retención de Clientes',
    'staff.performance.popularServices': 'Servicios Populares',
    'staff.performance.monthlyGoals': 'Metas Mensuales',
    'staff.performance.revenueGoal': 'Meta de Ingresos',
    'staff.performance.appointmentsGoal': 'Meta de Citas',
    'staff.performance.ratingGoal': 'Meta de Calificación',
    'staff.days.monday': 'Lunes',
    'staff.days.tuesday': 'Martes',
    'staff.days.wednesday': 'Miércoles',
    'staff.days.thursday': 'Jueves',
    'staff.days.friday': 'Viernes',
    'staff.days.saturday': 'Sábado',
    'staff.days.sunday': 'Domingo',

    // Admin Page
    'admin.title': 'Panel de Administración',
    'admin.subtitle': 'Gestiona todas las citas del salón',
    'admin.stats.total': 'Total Citas',
    'admin.stats.pending': 'Pendientes',
    'admin.stats.confirmed': 'Confirmadas',
    'admin.stats.completed': 'Completadas',
    'admin.filter.all': 'Todas',
    'admin.filter.pending': 'Pendiente',
    'admin.filter.confirmed': 'Confirmada',
    'admin.filter.completed': 'Completada',
    'admin.filter.canceled': 'Cancelada',
    'admin.noAppointments': 'No hay citas en esta categoría',
    'admin.client': 'Cliente',
    'admin.notes': 'Notas',
    'admin.actions.confirm': 'Confirmar',
    'admin.actions.complete': 'Completar',
    'admin.actions.cancel': 'Cancelar',
    'admin.actions.delete': 'Eliminar',
    'admin.deleteConfirm': '¿Estás seguro de eliminar esta cita?',
    'admin.status.pending': 'Pendiente',
    'admin.status.confirmed': 'Confirmada',
    'admin.status.completed': 'Completada',
    'admin.status.canceled': 'Cancelada',

    // Booking Page (New)
    'booking.new.title': 'Reserva tu Cita',
    'booking.new.subtitle': 'Selecciona tu servicio y hora preferida',
    'booking.new.success': '¡Cita reservada exitosamente! Te contactaremos pronto para confirmar.',
    'booking.new.personalInfo': 'Información Personal',
    'booking.new.fullName': 'Nombre Completo',
    'booking.new.fullNamePlaceholder': 'Tu nombre completo',
    'booking.new.phone': 'Teléfono',
    'booking.new.phonePlaceholder': '(555) 123-4567',
    'booking.new.email': 'Correo Electrónico',
    'booking.new.emailPlaceholder': 'tu@correo.com',
    'booking.new.selectService': 'Selecciona un Servicio',
    'booking.new.dateTime': 'Fecha y Hora',
    'booking.new.date': 'Fecha',
    'booking.new.time': 'Hora',
    'booking.new.selectTime': 'Selecciona una hora',
    'booking.new.additionalNotes': 'Notas Adicionales (Opcional)',
    'booking.new.notesPlaceholder': '¿Alguna preferencia o solicitud especial?',
    'booking.new.bookButton': 'Reservar Cita',
    'booking.new.booking': 'Reservando...',
    'booking.new.required': '*',

    // Gallery Page
    'gallery.title': 'Galería de Nuestro Trabajo',
    'gallery.subtitle': 'Explora nuestras impresionantes transformaciones e inspírate para tu próximo viaje de belleza',
    'gallery.searchPlaceholder': 'Buscar por estilo, servicio o etiqueta...',
    'gallery.filter': 'Filtrar',
    'gallery.categories': 'Categorías',
    'gallery.allWork': 'Todos los Trabajos',
    'gallery.hairCuts': 'Cortes de Cabello',
    'gallery.hairColor': 'Color de Cabello',
    'gallery.viewDetails': 'Ver Detalles',
    'gallery.noResults': 'No se encontraron resultados',
    'gallery.noResultsDesc': 'Intenta ajustar tu búsqueda o criterios de filtro para encontrar lo que buscas.',
    'gallery.cta.title': '¿Lista para Tu Transformación?',
    'gallery.cta.subtitle': 'Reserva tu cita hoy y deja que nuestros expertos creen tu look perfecto',
    'gallery.cta.book': 'Reservar Ahora',
    'gallery.cta.instagram': 'Síguenos en Instagram',

    // Footer
    'footer.description': 'Experimenta servicios de belleza de lujo con cuidado personalizado en nuestro ambiente de salón moderno. Tu transformación de belleza te espera.',
    'footer.hours': 'Horario',
    'footer.monday': 'Lun - Vie',
    'footer.saturday': 'Sábado',
    'footer.sunday': 'Domingo',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.cancellation': 'Política de Cancelación',

    // Common
    'common.book': 'Reservar',
    'common.learnMore': 'Saber Más',
    'common.price': 'Precio',
    'common.duration': 'Duración',
    'common.contact': 'Contáctanos',
    'common.required': '*',
    'common.at': 'a las',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'es'>('es');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'es' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
